name: Docker

on:
  workflow_dispatch:
    inputs:
      runnerConfigUrl:
        description: 'URL for configuring runner'
        required: true

  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

jobs:
  build_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/github-script@v3.0.0
        with:
          debug: true
          script: |
            var latestRelease = await github.repos.getLatestRelease({
              "actions",
              "runner"
            })
            console.log(latestRelease.data)
        env:
          RUNNER_URL: ${{github.event.inputs.runnerConfigUrl}}
      - run: |
          docker build -t huangtingluo/k8s-runner-image:latest . --file Dockerfile
          
      - uses: docker/login-action@v1.3.0
        with:
          username: huangtingluo
          password: ${{secrets.docker_cred}}
      
      - run: |
         docker push huangtingluo/k8s-runner-image:latest
