name: Docker

on:
  workflow_dispatch:
    inputs:
      runnerDownloadUrl:
        description: 'Overwrite runner download url from http://github.com/actions/runner/releases'     

  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

jobs:
  build_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - run: |
          ./download-runner.sh
        env:
          RUNNER_DOWNLOAD_URL: ${{ github.event.inputs.runnerDownloadUrl }}

      - run: |
          docker build -t huangtingluo/k8s-runner-image:latest . --file Dockerfile
          
      - uses: docker/login-action@v1.3.0
        with:
          username: huangtingluo
          password: ${{secrets.docker_cred}}
      
      - run: |
         docker push huangtingluo/k8s-runner-image:latest
